# Weather presets for CARLA environment for random weather selection each episode
presets:
  clear_noon:
    cloudiness: 0.0
    precipitation: 0.0
    precipitation_deposits: 0.0
    wind_intensity: 0.0
    sun_altitude_angle: 90.0
    sun_azimuth_angle: 0.0
    fog_density: 0.0
    wetness: 0.0

  clear_sunset:
    cloudiness: 10.0
    precipitation: 0.0
    precipitation_deposits: 0.0
    wind_intensity: 5.0
    sun_altitude_angle: 15.0
    sun_azimuth_angle: 270.0
    fog_density: 0.0
    wetness: 0.0